# Generated by Django 4.2.3 on 2023-07-15 07:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 15, 7, 13, 37, 908890, tzinfo=datetime.timezone.utc)),
        ),
    ]
