# Generated by Django 4.2.3 on 2023-07-16 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_comment_date_alter_comment_img_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 16, 19, 50, 44, 144043, tzinfo=datetime.timezone.utc)),
        ),
    ]
