# Generated by Django 4.2.3 on 2023-07-16 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_chat_direction_alter_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='userip',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 16, 20, 26, 49, 320105, tzinfo=datetime.timezone.utc)),
        ),
    ]
