# Generated by Django 4.2.3 on 2023-07-18 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_chat_time_alter_chat_user_alter_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 18, 12, 11, 22, 331948, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 7, 18, 12, 11, 22, 331948, tzinfo=datetime.timezone.utc)),
        ),
    ]
